spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/picnetdb
    username: postgres
    password: debd1867
  flyway:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:

picnet:
  pic-on-page: 4
  top-user: 5